ESX = exports['es_extended']:getSharedObject()

ESX.RegisterUsableItem('pistol-ammobox', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.addInventoryItem('pistol-ammo', 20)
    TriggerClientEvent('esx:showNotification', source, '20 darab lőszert szedtél ki a dobozból!')
    xPlayer.removeInventoryItem('ammobox', 1)
end)

-- ESX.RegisterUsableItem('rifle-ammobox', function(source)
--     local xPlayer = ESX.GetPlayerFromId(source)
--     xPlayer.addInventoryItem('rifle-ammo', 20)
--     TriggerClientEvent('esx:showNotification', source, '20 darab lőszert szedtél ki a dobozból!')
--     xPlayer.removeInventoryItem('rifle-ammobox', 1)
-- end)

-- ESX.RegisterUsableItem('shotgun-ammobox', function(source)
--     local xPlayer = ESX.GetPlayerFromId(source)
--     xPlayer.addInventoryItem('shotgun-ammo', 20)
--     TriggerClientEvent('esx:showNotification', source, '20 darab lőszert szedtél ki a dobozból!')
--     xPlayer.removeInventoryItem('shotgun-ammobox', 1)
-- end)

-- ESX.RegisterUsableItem('smg-ammobox', function(source)
--     local xPlayer = ESX.GetPlayerFromId(source)
--     xPlayer.addInventoryItem('smg-ammo', 20)
--     TriggerClientEvent('esx:showNotification', source, '20 darab lőszert szedtél ki a dobozból!')
--     xPlayer.removeInventoryItem('smg-ammobox', 1)
-- end)